#!/bin/bash

echo "🔧 CareRide Local Email Setup Guide"
echo "===================================="
echo ""
echo "To enable email functionality in local development, follow these steps:"
echo ""
echo "1️⃣  Set up Gmail App Password:"
echo "   • Go to: https://myaccount.google.com/security"
echo "   • Enable 2-Factor Authentication if not already enabled"
echo "   • Go to: https://myaccount.google.com/apppasswords"
echo "   • Generate an App Password for 'Mail'"
echo "   • Copy the 16-character app password"
echo ""
echo "2️⃣  Set Environment Variables:"
echo "   Run these commands in your terminal:"
echo ""
echo "   export MAIL_USERNAME=\"your-email@gmail.com\""
echo "   export MAIL_PASSWORD=\"your-16-char-app-password\""
echo ""
echo "3️⃣  Restart the Backend:"
echo "   • Stop the current backend (Ctrl+C)"
echo "   • Run: mvn spring-boot:run -Dspring-boot.run.profiles=local"
echo ""
echo "4️⃣  Test Email:"
echo "   • Go to http://localhost:4200/contact"
echo "   • Fill out and submit the form"
echo "   • Check your email for the notification"
echo ""
echo "🔒 Security Note:"
echo "   • App passwords are safer than using your main Gmail password"
echo "   • Never commit real credentials to version control"
echo "   • Use environment variables for sensitive data"
echo ""
echo "📧 Alternative: Use AWS WorkMail (Production Settings)"
echo "   The app is configured to use AWS WorkMail in production."
echo "   For local testing, Gmail is easier to set up."
echo ""
